//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BirthDay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class get_ok_days
    {
        public string fio { get; set; }
        public int tabn { get; set; }
        //public Nullable<System.DateTime> datbegin { get; set; }
        public DateTime datbegin { get; set; }
        public string FullPodr { get; set; }
        public string doljn { get; set; }
        public Nullable<System.Guid> id_0 { get; set; }
        public Nullable<System.Guid> id_1 { get; set; }
        public Nullable<System.Guid> id_2 { get; set; }
        public Nullable<System.Guid> id_3 { get; set; }
        public Nullable<System.Guid> id_4 { get; set; }
        public Nullable<int> dday { get; set; }
        public Nullable<int> dmonth { get; set; }

        public int Aget { get { return DateTime.Now.Year - Convert.ToInt32(datbegin.Year); } }
        public int Aget1 { get { return DateTime.Now.Year - Convert.ToInt32(datbegin.Year) - 1; } }
        public int NowKol { get { return (DateTime.Now.Month-1) * 30 + DateTime.Now.Day; } }
        public int BirdKol { get { return (datbegin.Month-1) * 30 + datbegin.Day; } }
    }
}
